//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class err_cat
    {
        public err_cat()
        {
            this.err_typ = new HashSet<err_typ>();
        }
    
        public int err_cat_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public string err_cat_nm { get; set; }
        public string err_cat_desc { get; set; }
    
        public virtual ICollection<err_typ> err_typ { get; set; }
    }
}
