//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class inst
    {
        public inst()
        {
            this.tgt_inst = new HashSet<tgt_inst>();
            this.src_inst_xref = new HashSet<src_inst_xref>();
        }
    
        public int inst_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public int syst_skey { get; set; }
        public string inst_nm { get; set; }
        public string inst_desc { get; set; }
        public string inst_typ { get; set; }
        public string inst_file_locn { get; set; }
        public string inst_file_nm { get; set; }
        public string inst_server_locn { get; set; }
        public string inst_db_nm { get; set; }
        public string inst_tble_nm { get; set; }
        public string inst_tble_locn { get; set; }
    
        public virtual syst syst { get; set; }
        public virtual ICollection<tgt_inst> tgt_inst { get; set; }
        public virtual ICollection<src_inst_xref> src_inst_xref { get; set; }
    }
}
