//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public job()
        {
            this.parm_ctrl = new HashSet<parm_ctrl>();
            this.job_det = new HashSet<job_det>();
            this.run_job_stats = new HashSet<run_job_stats>();
        }
    
        public int job_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public int job_typ_skey { get; set; }
        public int fldr_skey { get; set; }
        public string job_nm { get; set; }
        public string job_desc { get; set; }
        public Nullable<int> row_cnt_thrshld { get; set; }
        public Nullable<int> norm_run_tm { get; set; }
        public Nullable<int> max_run_tm { get; set; }
        public Nullable<int> do_not_run_after { get; set; }
        public string job_schd_nm { get; set; }
    
        public virtual fldr fldr { get; set; }
        public virtual job_typ job_typ { get; set; }
        public virtual ICollection<parm_ctrl> parm_ctrl { get; set; }
        public virtual ICollection<job_det> job_det { get; set; }
        public virtual ICollection<run_job_stats> run_job_stats { get; set; }
    }
}
