//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_det
    {
        public job_det()
        {
            this.run_job_det_stats = new HashSet<run_job_det_stats>();
            this.tgt_inst = new HashSet<tgt_inst>();
            this.src_inst = new HashSet<src_inst>();
            this.parm_ctrl = new HashSet<parm_ctrl>();
        }
    
        public int job_det_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public int job_skey { get; set; }
        public string job_det_nm { get; set; }
        public string job_det_desc { get; set; }
        public string job_det_map_nm { get; set; }
    
        public virtual job job { get; set; }
        public virtual ICollection<run_job_det_stats> run_job_det_stats { get; set; }
        public virtual ICollection<tgt_inst> tgt_inst { get; set; }
        public virtual ICollection<src_inst> src_inst { get; set; }
        public virtual ICollection<parm_ctrl> parm_ctrl { get; set; }
    }
}
