//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class parm_ctrl
    {
        public parm_ctrl()
        {
            this.run_parm_stats = new HashSet<run_parm_stats>();
        }
    
        public int parm_ctrl_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public Nullable<int> job_skey { get; set; }
        public Nullable<int> job_det_skey { get; set; }
        public string parm_nm { get; set; }
        public string parm_desc { get; set; }
        public string static_ind { get; set; }
        public string parm_lst_run_val { get; set; }
    
        public virtual job job { get; set; }
        public virtual job_det job_det { get; set; }
        public virtual ICollection<run_parm_stats> run_parm_stats { get; set; }
    }
}
