//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class src_inst
    {
        public src_inst()
        {
            this.run_src_stats = new HashSet<run_src_stats>();
            this.src_inst_xref = new HashSet<src_inst_xref>();
        }
    
        public int src_inst_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public int job_det_skey { get; set; }
        public string src_inst_nm { get; set; }
        public string src_inst_desc { get; set; }
    
        public virtual job_det job_det { get; set; }
        public virtual ICollection<run_src_stats> run_src_stats { get; set; }
        public virtual ICollection<src_inst_xref> src_inst_xref { get; set; }
    }
}
