//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tgt_inst
    {
        public tgt_inst()
        {
            this.run_tgt_stats = new HashSet<run_tgt_stats>();
        }
    
        public int tgt_inst_skey { get; set; }
        public string aud_ins_id { get; set; }
        public string aud_upd_id { get; set; }
        public System.DateTime aud_ins_tmstp { get; set; }
        public System.DateTime aud_upd_tmstp { get; set; }
        public string actv_ind { get; set; }
        public int job_det_skey { get; set; }
        public int inst_skey { get; set; }
        public string tgt_inst_nm { get; set; }
        public string tgt_inst_desc { get; set; }
    
        public virtual inst inst { get; set; }
        public virtual job_det job_det { get; set; }
        public virtual ICollection<run_tgt_stats> run_tgt_stats { get; set; }
    }
}
